import {
    TrendingUp,
    CheckCircle,
    CreditCard,
    Globe,
    Factory,
    Truck,
    Leaf,
    FileText,
    BarChart3,
    Upload,
    Banknote,
} from "lucide-react";
export const financingProducts = [
    {
        id: 1,
        title: "Working Capital Loans",
        description:
            "Short-term financing for day-to-day operations, inventory, and cash flow management",
        minAmount: "$10,000",
        maxAmount: "$500,000",
        term: "6-24 months",
        interestRate: "7.5% - 12%",
        features: [
            "Quick approval",
            "Flexible repayment",
            "No collateral required",
            "Digital application",
        ],
        eligibility: [
            "2+ years in business",
            "Annual revenue $50K+",
            "Good credit history",
        ],
        icon: CreditCard,
        color: "bg-blue-500",
        popular: true,
    },
    {
        id: 2,
        title: "Export Finance",
        description:
            "Specialized financing for export-oriented SMEs to expand into international markets",
        minAmount: "$25,000",
        maxAmount: "$2,000,000",
        term: "12-60 months",
        interestRate: "6.5% - 10%",
        features: [
            "Pre-shipment finance",
            "Post-shipment finance",
            "Letter of credit",
            "Export insurance",
        ],
        eligibility: [
            "Export experience",
            "Valid export contracts",
            "Export license",
        ],
        icon: Globe,
        color: "bg-green-500",
        popular: false,
    },
    {
        id: 3,
        title: "Equipment Finance",
        description:
            "Financing for machinery, equipment, and technology to modernize your operations",
        minAmount: "$15,000",
        maxAmount: "$1,000,000",
        term: "24-84 months",
        interestRate: "8% - 14%",
        features: [
            "Up to 90% financing",
            "Equipment as collateral",
            "Flexible terms",
            "Technology upgrades",
        ],
        eligibility: [
            "Equipment quotation",
            "Business plan",
            "Financial statements",
        ],
        icon: Factory,
        color: "bg-purple-500",
        popular: false,
    },
    {
        id: 4,
        title: "Trade Finance",
        description:
            "Comprehensive trade financing solutions for import and export transactions",
        minAmount: "$20,000",
        maxAmount: "$5,000,000",
        term: "3-36 months",
        interestRate: "5.5% - 9%",
        features: [
            "Letters of credit",
            "Bank guarantees",
            "Documentary collections",
            "Trade credit insurance",
        ],
        eligibility: ["Trade experience", "Valid contracts", "Credit assessment"],
        icon: Truck,
        color: "bg-orange-500",
        popular: false,
    },
    {
        id: 5,
        title: "Green Finance",
        description:
            "Sustainable financing for environmentally friendly and climate-smart projects",
        minAmount: "$30,000",
        maxAmount: "$3,000,000",
        term: "36-120 months",
        interestRate: "6% - 11%",
        features: [
            "Preferential rates",
            "Green certification",
            "Impact measurement",
            "Technical assistance",
        ],
        eligibility: [
            "Environmental impact",
            "Green certification",
            "Sustainability plan",
        ],
        icon: Leaf,
        color: "bg-emerald-500",
        popular: false,
    },
    {
        id: 6,
        title: "SME Growth Capital",
        description:
            "Long-term financing for business expansion, acquisitions, and strategic investments",
        minAmount: "$100,000",
        maxAmount: "$10,000,000",
        term: "36-120 months",
        interestRate: "9% - 15%",
        features: [
            "Flexible structure",
            "Growth advisory",
            "Milestone-based",
            "Equity options",
        ],
        eligibility: ["Growth plan", "Management team", "Market opportunity"],
        icon: TrendingUp,
        color: "bg-indigo-500",
        popular: false,
    },
];
export const applicationProcess = [
    {
        step: 1,
        title: "Pre-Application",
        description:
            "Complete eligibility assessment and gather required documents",
        duration: "1-2 days",
        icon: FileText,
        tasks: [
            "Eligibility check",
            "Document preparation",
            "Business plan review",
        ],
    },
    {
        step: 2,
        title: "Application Submission",
        description: "Submit complete application through our digital platform",
        duration: "1 day",
        icon: Upload,
        tasks: [
            "Online application",
            "Document upload",
            "Application fee payment",
        ],
    },
    {
        step: 3,
        title: "Credit Assessment",
        description:
            "Comprehensive evaluation of creditworthiness and business viability",
        duration: "5-10 days",
        icon: BarChart3,
        tasks: [
            "Credit scoring",
            "Financial analysis",
            "Risk assessment",
            "Due diligence",
        ],
    },
    {
        step: 4,
        title: "Approval & Documentation",
        description: "Loan approval and completion of legal documentation",
        duration: "3-5 days",
        icon: CheckCircle,
        tasks: [
            "Approval decision",
            "Terms negotiation",
            "Legal documentation",
            "Collateral registration",
        ],
    },
    {
        step: 5,
        title: "Disbursement",
        description: "Fund disbursement to your designated bank account",
        duration: "1-2 days",
        icon: Banknote,
        tasks: [
            "Final verification",
            "Fund transfer",
            "Disbursement confirmation",
        ],
    },
];
export const partnerBanks = [
    {
        name: "First Bank of Nigeria",
        country: "Nigeria",
        products: ["Working Capital", "Export Finance", "Trade Finance"],
        disbursed: "$45M",
        smes: 1250,
        rating: 4.8,
        logo: "/placeholder.svg?height=60&width=120&text=First+Bank",
    },
    {
        name: "Standard Bank",
        country: "South Africa",
        products: ["Equipment Finance", "Growth Capital", "Green Finance"],
        disbursed: "$38M",
        smes: 890,
        rating: 4.7,
        logo: "/placeholder.svg?height=60&width=120&text=Standard+Bank",
    },
    {
        name: "Equity Bank",
        country: "Kenya",
        products: ["Working Capital", "SME Growth", "Trade Finance"],
        disbursed: "$32M",
        smes: 1100,
        rating: 4.9,
        logo: "/placeholder.svg?height=60&width=120&text=Equity+Bank",
    },
    {
        name: "Ecobank",
        country: "Multi-Country",
        products: ["Export Finance", "Working Capital", "Equipment Finance"],
        disbursed: "$28M",
        smes: 750,
        rating: 4.6,
        logo: "/placeholder.svg?height=60&width=120&text=Ecobank",
    },
];
export const successStories = [
    {
        company: "TechnoAfrica Solutions",
        founder: "Kwame Asante",
        country: "Ghana",
        sector: "Technology",
        loanAmount: "$150,000",
        loanType: "Working Capital",
        impact: "Expanded to 3 new countries, increased revenue by 250%",
        image: "/placeholder.svg?height=80&width=80&text=TA",
    },
    {
        company: "Green Energy Ltd",
        founder: "Fatima Al-Rashid",
        country: "Morocco",
        sector: "Renewable Energy",
        loanAmount: "$500,000",
        loanType: "Green Finance",
        impact: "Installed 50MW solar capacity, created 200 jobs",
        image: "/placeholder.svg?height=80&width=80&text=GE",
    },
    {
        company: "Export Textiles Co",
        founder: "John Mwangi",
        country: "Kenya",
        sector: "Manufacturing",
        loanAmount: "$300,000",
        loanType: "Export Finance",
        impact: "Increased exports by 400%, entered European markets",
        image: "/placeholder.svg?height=80&width=80&text=ET",
    },
];